version: 2
jobs:
  sslcheck:
    docker:
      - image: circleci/python:3.8.0-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check SSL Certificates
          command: |
            DATE=`date "+%Y%m%d-%H%M"`
            .circleci/slack-message.sh "*Checking SSL Certificates*: Begin" "MASTER" $DATE "#ffff00"
            sudo pip install -r requirements.txt
            ./ssl_checker.py -f /data/hosts_to_check
            .circleci/slack-message.sh "*Checked SSL Certificates*: Finished :key:" "MASTER" $DATE "#008000"

workflows:
  version: 2
  sslcheck-on-push:
    jobs:
      - sslcheck:
        #TODO: Change context
          context: github-backup
          filters:
            branches:
              only: master
  sslcheck-on-schedule:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sslcheck:
        #TODO: Change context
          context: github-backup
          filters:
            branches:
              only: master
