version: 2
jobs:
  sslcheck:
    docker:
      - image: circleci/python:3.8.0-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check SSL Certificates
          command: |
            set -e
            sudo pip install -r requirements.txt
            OUTPUT=$(./ssl_checker.py -f ./hosts_to_check)
            echo "$OUTPUT"
            if ! [[ echo "$OUTPUT" | grep "Expired: 0" ]]; then
              .circleci/slack-message.sh "*Checked SSL Certificates*: Expired :x:" "MASTER" $DATE "#FF0000"
            elif ! [[ echo "$OUTPUT" | grep "Warning: 0" ]]; then
              .circleci/slack-message.sh "*Checked SSL Certificates*: Warnings :warning:" "MASTER" $DATE "#FFFF00"
            else
              .circleci/slack-message.sh "*Checked SSL Certificates*: Success :key:" "MASTER" $DATE "#008000"
            fi

workflows:
  version: 2
  sslcheck-on-push:
    jobs:
      - sslcheck:
        #TODO: Change context
          context: github-backup
          filters:
            branches:
              only: master
  sslcheck-on-schedule:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - sslcheck:
        #TODO: Change context
          context: github-backup
          filters:
            branches:
              only: master
